genres_id_to_name_dict = {
    2: 'Point-and-click',
    4: 'Fighting',
    5: 'Shooter',
    7: 'Music',
    8: 'Platform',
    9: 'Puzzle',
    10: 'Racing',
    11: 'RTS',
    12: 'RPG',
    13: 'Simulator',
    14: 'Sport',
    15: 'Strategy',
    16: 'TBS',
    24: 'Tactical',
    25: "Hack and slash or Beat'em up",
    26: 'Quiz or Trivia',
    30: 'Pinball',
    31: 'Adventure',
    32: 'Indie',
    33: 'Arcade',
    34: 'Visual Novel',
    35: 'Card & Board',
    36: 'MOBA'
}